
project_id = "lqjtzgkqggojssfezior"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[functions.check-expiring-receipts]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-notification-sms]
verify_jwt = false

[functions.scheduled-notifications]
verify_jwt = false

[auth]
enabled = true
port = 54320
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lqjtzgkqggojssfezior.supabase.co/**"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[edge_runtime]
enabled = true
port = 54326
policy = "per_worker"
inspector_port = 8083
