// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqjtzgkqggojssfezior.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxanR6Z2txZ2dvanNzZmV6aW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzQzNTIsImV4cCI6MjA2MjQ1MDM1Mn0.9ei_VPhYbuBJM_CseufmBBP3kobkcLEftAspoHGggJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);